name: CI

on:
  push:
    branches:
      - develop

jobs:
  flake8StyleCheck:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install flake8
        run: pip install flake8

      - name: Style & lint check
        run: flake8

  editorconfigStyleCheck:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install editorconfig-checker
        run: npm install -g editorconfig-checker

      - name: .editorconfig check
        run: editorconfig-checker

  makrdownlintStyleCheck:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Markdown files check
        run: markdownlint '**/*.md'
